#!/usr/bin/env bash

export BASE_IMAGE_FULL_TAG="ghcr.io/${REPOSITORY_USER,,}/$BASE_IMAGE_NAME:$BASE_IMAGE_RELEASE_TAG"
export IMAGE_FULL_TAG="ghcr.io/${REPOSITORY_USER,,}/$IMAGE_NAME:$IMAGE_RELEASE_TAG"
export REPOSITORY_URL="https://github.com/${REPOSITORY_USER}/${REPOSITORY_NAME}"
